# Generated by Django 5.2.1 on 2025-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('purchase_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('purchased_kitta', models.PositiveIntegerField()),
                ('purchase_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('opportunity_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sold_kitta', models.PositiveIntegerField(blank=True, null=True)),
                ('sale_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
