# Generated by Django 5.2.2 on 2025-06-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=150)),
                ('script', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('transaction', models.CharField(choices=[('Buy', 'Buy'), ('Sale', 'Sale'), ('balance b/d', 'Balance b/d'), ('IPO', 'IPO'), ('FPO', 'FPO'), ('Bonus', 'Bonus'), ('Right', 'Right'), ('Conversion(+)', 'Conversion(+)'), ('Conversion(-)', 'Conversion(-)'), ('Suspense(+)', 'Suspense(+)'), ('Suspense(-)', 'Suspense(-)')], default='Buy', max_length=20)),
                ('kitta', models.IntegerField()),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broker', models.CharField(max_length=50)),
                ('unique_id', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('entry', models.OneToOneField(db_column='entry_unique_id', default='00000000abc', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.entrysheet', to_field='unique_id')),
                ('op_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('op_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('op_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('p_qty', models.IntegerField(default=0)),
                ('p_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('p_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('s_qty', models.IntegerField(default=0)),
                ('s_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('s_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cl_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cl_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cl_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
        ),
    ]
