# Generated by Django 5.2.1 on 2025-06-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=10)),
                ('script', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buy'), ('Sale', 'Sale')], max_length=4)),
                ('kitta', models.PositiveIntegerField()),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('broker', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
