# Generated by Django 5.2.1 on 2025-06-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_entrysheet_delete_stocktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrysheet',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='entrysheet',
            name='transaction',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sale', 'Sale'), ('Balance bd', 'Balance b/d'), ('IPO', 'IPO'), ('FPO', 'FPO'), ('Bonus', 'Bonus'), ('Right', 'Right'), ('Conversion(+)', 'Conversion(+)'), ('Conversion(-)', 'Conversion(-)'), ('Suspense(+)', 'Suspense(+)'), ('Suspense(-)', 'Suspense(-)')], default='Buy', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrysheet',
            name='billed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entrysheet',
            name='broker',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entrysheet',
            name='kitta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='entrysheet',
            name='script',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entrysheet',
            name='sector',
            field=models.CharField(max_length=50),
        ),
    ]
