# Generated by Django 5.2.1 on 2025-06-05 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_entrysheet_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('t_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('op_qty', models.IntegerField(default=0)),
                ('op_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('op_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('p_qty', models.IntegerField(default=0)),
                ('p_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('p_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('s_qty', models.IntegerField(default=0)),
                ('s_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('s_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cl_qty', models.IntegerField(default=0)),
                ('cl_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cl_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_entries', to='cms.entrysheet')),
            ],
        ),
    ]
